
create database futmesacartola;
use futmesacartola;
create table Usuario (
		US_USID int AUTO_INCREMENT PRIMARY KEY,
		US_USLOGIN  VARCHAR(300) not null,
        US_USSENHA  VARCHAR(300) not null,
        US_USATIVO  boolean,
        US_USNOMETRATAMENTO VARCHAR(300) not null,
        US_CLID int ,
        US_GUID int ,
        US_USEMAIL VARCHAR(300) not null,
        US_USDATACADASTRO  Date);
ALTER TABLE Usuario ADD UNIQUE (US_USLOGIN);
ALTER TABLE Usuario ADD UNIQUE (US_USEMAIL);

use futmesacartola;
ALTER TABLE Usuario ADD CONSTRAINT FK_Usuario_Clube FOREIGN KEY (US_CLID) REFERENCES Clubes(CL_CLID); 
ALTER TABLE Usuario ADD CONSTRAINT FK_Usuario_Grupousuario FOREIGN KEY (US_GUID) REFERENCES GRUPOUSUARIO(GU_GUID);

create table Clubes (
		CL_CLID int AUTO_INCREMENT PRIMARY KEY,
		CL_CLNOME  VARCHAR(300) not null,
        CL_CLENDERECO  VARCHAR(300) null,
        CL_CLCIDADE VARCHAR(300) NULL,
        CL_CLUF VARCHAR(2) NULL,
        CL_CLATIVO  boolean,
        CL_CLSIGLA  VARCHAR(5) not null,
        CL_CLEMBLEMA VARCHAR(300) NULL ,
        CL_CLEMAIL VARCHAR(300) not null,
        CL_CLRESPONSAVEL VARCHAR(300) not null,
        CL_CLDATACADASTRO  Date,
        CL_CLTELEFONE varchar(300));
use futmesacartola;
ALTER TABLE Clubes ADD CONSTRAINT FK_Clube_Estados FOREIGN KEY (CL_CLUF) REFERENCES estados(UF_UFSIGLA);
use futmesacartola;
INSERT INTO CLUBES (CL_CLNOME,CL_CLENDERECO,CL_CLCIDADE,CL_CLUF,CL_CLATIVO,CL_CLSIGLA,CL_CLEMBLEMA,CL_CLEMAIL,CL_CLRESPONSAVEL,CL_CLDATACADASTRO,CL_CLTELEFONE )
VALUES ('Fedeeração Paulista de Futebol de Mesa','Rua Costa Aguiar, 232 - Ipiranga','São Paulo - Ipiranga','SP',1,'FPFM','assets/images/logos clubes/fpfm.png','FUTMESA@FUTMESA.COM.BR','FARAH12','2020-05-25','12121');

use futmesacartola;
create table estados (
		UF_UFID int AUTO_INCREMENT PRIMARY KEY,
		UF_UFNOME  VARCHAR(300) not null,
        UF_UFSIGLA  VARCHAR(300) null);
        
insert into estados (UF_UFNOME,UF_UFSIGLA)values ('AMAZONAS','AM') ;       
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('PARA','PA');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('RONDONIA','RO');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('ACRE','AC');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('RORAIMA','RR');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('MATO GROSSO','MT');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('GOIAS','GO');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('MATO GROSSO DO SUL','MS');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('TOCANTINS','TO');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('AMAPA','AP');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('BRASILIA','DF');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('SÃO PAULO','SP');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('PARANA','PR');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('ESPIRITO SANTO','ES');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('RIO DE JANEIRO','RJ');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('MINAS GERAIS','MG');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('SANTA CATARINA','SC');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('RIO GRANDE DO SUL','RS');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('BAHIA','BA');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('ALAGOAS','AL');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('SERGIPE','SE');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('PERNAMBUCO','PE');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('PARAIBA','PB');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('RIO GRANDE DO NORTE','RN');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('CEARA','CE');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('MARANHÃP','MA');
insert into estados (UF_UFNOME,UF_UFSIGLA) values ('PIAUI','PI');
USE FUTMESACARTOLA;                
SELECT * FROM ESTADOS;   

USE FUTMESACARTOLA; 
CREATE TABLE GRUPOUSUARIO 
(
	GU_GUID int AUTO_INCREMENT PRIMARY KEY,
	GU_GUDESCRICAO  VARCHAR(300) not null,
	CL_CLENDERECO  VARCHAR(300) null,
	GU_GUATIVO  boolean,
	CL_CLSIGLA  VARCHAR(5) not null,
	GU_GUDATACADASTRO  Date );

INSERT INTO grupousuario VALUES ('ADMINISTRADOR',1,NOW());
INSERT INTO grupousuario VALUES ('CLUBE',1,NOW());
INSERT INTO grupousuario VALUES ('USUARIO',1,NOW());
INSERT INTO grupousuario VALUES ('JOGADOR',1,NOW());

USE FUTMESACARTOLA;
CREATE TABLE Jogador (
        JO_JOID int AUTO_INCREMENT PRIMARY KEY,
        JO_JONOME VARCHAR(300) not null,
        JO_JOFOTO VARCHAR(300) ,
        JO_JOAPELIDO VARCHAR(50) not null,
        JO_JOATIVO boolean,
        JO_CLID int,
        JO_JODATACADASTRO Date
    );

USE FUTMESACARTOLA; 
ALTER TABLE Jogador ADD CONSTRAINT FK_Jogador_clubes FOREIGN KEY (JO_CLID) REFERENCES Clubes(CL_CLID);

USE FUTMESACARTOLA;
INSERT INTO Jogador ( JO_JONOME,JO_JOFOTO,JO_JOAPELIDO,JO_JOATIVO, JO_CLID,JO_JODATACADASTRO) VALUES ('Jorge Farah',null,'Farah', 1, 1, '2020-08-07');   

USE FUTMESACARTOLA;
select * from Jogador;

USE FUTMESACARTOLA;
CREATE TABLE HistoricoJogador (
        HJ_HJID int AUTO_INCREMENT PRIMARY KEY,
        HJ_JOID INT not null,
        HJ_JOAPELIDO VARCHAR(50) not null,
        HJ_JOATIVO boolean,
        HJ_CLID int NOT NULL,
        HJ_HJDATACADASTRO Datetime NOT NULL
    );
    
USE FUTMESACARTOLA; 
ALTER TABLE HistoricoJogador ADD CONSTRAINT FK_HistoricoJogador_Jogador FOREIGN KEY (HJ_JOID) REFERENCES Jogador(JO_JOID);
ALTER TABLE HistoricoJogador ADD CONSTRAINT FK_HistoricoJogador_clubes FOREIGN KEY (HJ_CLID) REFERENCES Clubes(CL_CLID);

USE FUTMESACARTOLA;
CREATE TABLE CATEGORIAJOGO (
        CJ_CJID int AUTO_INCREMENT PRIMARY KEY,
        CJ_CJDESCRICAO VARCHAR(100),
        CJ_CJATIVO boolean,
        CJ_CJDATACADASTRO Datetime NOT NULL
    );
 USE FUTMESACARTOLA;   
INSERT INTO  CATEGORIAJOGO (CJ_CJDESCRICAO, CJ_CJATIVO,CJ_CJDATACADASTRO) VALUES ('Equipes',1,now());
INSERT INTO  CATEGORIAJOGO (CJ_CJDESCRICAO, CJ_CJATIVO,CJ_CJDATACADASTRO) VALUES ('Abertos',1,now());
INSERT INTO  CATEGORIAJOGO (CJ_CJDESCRICAO, CJ_CJATIVO,CJ_CJDATACADASTRO) VALUES ('Challenger',1,now());

USE FUTMESACARTOLA;
CREATE TABLE JOGOS (
        JG_JGID int AUTO_INCREMENT PRIMARY KEY,
        JG_JGDATA datetime not null,
        JG_JOID1 INT NOT NULL,
        JG_JGGOL1 INT,
        JG_JGVITORIA1 INT,
        JG_JGEMPATE1 INT,
        JG_DERROTA1 INT,
        JG_JOID2 INT NOT NULL,
        JG_JGGOL2 INT,
        JG_JGVITORIA2 INT,
        JG_JGEMPATE2 INT,
        JG_DERROTA2 INT,
        JG_JGATIVO boolean,
		JG_JGDATACADASTRO Datetime
    );
    

USE FUTMESACARTOLA; 
CREATE TABLE RODADAS (
        RO_ROID int AUTO_INCREMENT PRIMARY KEY,
        RO_RODESCRICAO VARCHAR(50) not null,
        RO_ROATIVO boolean,
		RO_RODATACADASTRO Datetime
    );
INSERT INTO  RODADAS (RO_RODESCRICAO, RO_ROATIVO,RO_RODATACADASTRO) VALUES ('1º Rodada',1,now());
INSERT INTO  RODADAS (RO_RODESCRICAO, RO_ROATIVO,RO_RODATACADASTRO) VALUES ('2º Rodada',1,now());
INSERT INTO  RODADAS (RO_RODESCRICAO, RO_ROATIVO,RO_RODATACADASTRO) VALUES ('3º Rodada',1,now());
INSERT INTO  RODADAS (RO_RODESCRICAO, RO_ROATIVO,RO_RODATACADASTRO) VALUES ('4º Rodada',1,now());
INSERT INTO  RODADAS (RO_RODESCRICAO, RO_ROATIVO,RO_RODATACADASTRO) VALUES ('5º Rodada',1,now());
INSERT INTO  RODADAS (RO_RODESCRICAO, RO_ROATIVO,RO_RODATACADASTRO) VALUES ('6º Rodada',1,now());
INSERT INTO  RODADAS (RO_RODESCRICAO, RO_ROATIVO,RO_RODATACADASTRO) VALUES ('7º Rodada',1,now());
INSERT INTO  RODADAS (RO_RODESCRICAO, RO_ROATIVO,RO_RODATACADASTRO) VALUES ('8º Rodada',1,now());
INSERT INTO  RODADAS (RO_RODESCRICAO, RO_ROATIVO,RO_RODATACADASTRO) VALUES ('9º Rodada',1,now());
INSERT INTO  RODADAS (RO_RODESCRICAO, RO_ROATIVO,RO_RODATACADASTRO) VALUES ('10º Rodada',1,now());
INSERT INTO  RODADAS (RO_RODESCRICAO, RO_ROATIVO,RO_RODATACADASTRO) VALUES ('11º Rodada',1,now());
INSERT INTO  RODADAS (RO_RODESCRICAO, RO_ROATIVO,RO_RODATACADASTRO) VALUES ('12º Rodada',1,now());
INSERT INTO  RODADAS (RO_RODESCRICAO, RO_ROATIVO,RO_RODATACADASTRO) VALUES ('Aberto Ou Open',1,now());

USE FUTMESACARTOLA;
CREATE TABLE COMPETICOES (
        CP_CPID int AUTO_INCREMENT PRIMARY KEY,
        CP_CPCIDADE VARCHAR(200) not null,
        CP_CPDESCRICAO VARCHAR(200) not null,
        CP_CPFOTO VARCHAR(300),
        CP_ROID INT NOT NULL,
        CP_CPDATALIMITEAPOSTA DATETIME NOT NULL,
        CP_CPDATAINICIO DATETIME NOT NULL,
		CP_CJID int not null,
        CP_CPATIVO boolean,
		CP_CPDATACADASTRO Datetime
    );
    
USE FUTMESACARTOLA; 
ALTER TABLE COMPETICOES ADD CONSTRAINT FK_COMPETICOES_CategoriaJogos FOREIGN KEY (CP_CJID) REFERENCES CATEGORIAJOGO(CJ_CJID);
ALTER TABLE COMPETICOES ADD CONSTRAINT FK_COMPETICOES_Rodada FOREIGN KEY (CP_ROID) REFERENCES RODADAS(RO_ROID);

USE FUTMESACARTOLA;     
CREATE TABLE PTSCOMPETICOESJOGADORES (
        PJ_PJID int AUTO_INCREMENT PRIMARY KEY,
        PJ_CPID int not null,
        PJ_JOID int not null,
        PJ_PJPONTOS int,
        PJ_PJOBSERVACAO VARCHAR(300),
        PJ_PJATIVO boolean,
		PJ_PJDATACADASTRO Datetime
    );
    
USE FUTMESACARTOLA; 
ALTER TABLE PTSCOMPETICOESJOGADORES ADD CONSTRAINT FK_PTSCOMPETICOESJOGADORES_COMPETICOES FOREIGN KEY (PJ_CPID) REFERENCES COMPETICOES(CP_CPID);
ALTER TABLE PTSCOMPETICOESJOGADORES ADD CONSTRAINT FK_PTSCOMPETICOESJOGADORES_Jogador FOREIGN KEY (PJ_JOID) REFERENCES Jogador(JO_JOID);
ALTER TABLE PTSCOMPETICOESJOGADORES ADD CONSTRAINT UC_CompeticaoJogador UNIQUE (PJ_CPID,PJ_JOID); 

USE FUTMESACARTOLA;
CREATE TABLE RANKINGJOGADORES (
        RJ_RJID int AUTO_INCREMENT PRIMARY KEY,
        RJ_RJMES int not null,
        RJ_RJANO int not null,
        RJ_RJDATA date not null,
        RJ_JOID int not null,
        RJ_RJPOSICAO int,
        RJ_RJOBSERVACAO VARCHAR(300),
        RJ_RJATIVO boolean,
		RJ_RJDATACADASTRO Datetime
    );  
USE FUTMESACARTOLA; 
ALTER TABLE RANKINGJOGADORES ADD CONSTRAINT UC_RankingJogadorPosicao UNIQUE (RJ_RJMES,RJ_RJANO,RJ_RJPOSICAO,RJ_JOID); 
ALTER TABLE RANKINGJOGADORES ADD CONSTRAINT FK_RANKINGJOGADORES_Jogador FOREIGN KEY (RJ_JOID) REFERENCES Jogador(JO_JOID);
ALTER TABLE RANKINGJOGADORES ADD CONSTRAINT UC_RankingJogador UNIQUE (RJ_RJMES,RJ_RJANO,RJ_JOID); 
ALTER TABLE RANKINGJOGADORES ADD CONSTRAINT CHK_RankingJogadorMes CHECK (RJ_RJMES between 1 and 12); 
ALTER TABLE RANKINGJOGADORES ADD CONSTRAINT CHK_RankingJogadorAno CHECK (RJ_RJANO between 2000 and 3000);
 
 USE FUTMESACARTOLA;
  CREATE TABLE PRECORANKING (
        PR_PRID int AUTO_INCREMENT PRIMARY KEY,
        PR_PRPOSRANKING int not null,
        PR_PRPRECO int not null,
        PR_PROBSERVACAO VARCHAR(300),
        PR_PRATIVO boolean,
		PR_PRDATACADASTRO Datetime
    );  
 USE FUTMESACARTOLA;
 ALTER TABLE PRECORANKING ADD CONSTRAINT UC_PrecoRanking UNIQUE (PR_PRPOSRANKING,PR_PRPRECO); 
 
USE FUTMESACARTOLA;
INSERT INTO  PRECORANKING (PR_PRPOSRANKING,PR_PRPRECO,PR_PROBSERVACAO,PR_PRATIVO,PR_PRDATACADASTRO) VALUES (1,400,NULL,1,NOW());
INSERT INTO  PRECORANKING (PR_PRPOSRANKING,PR_PRPRECO,PR_PROBSERVACAO,PR_PRATIVO,PR_PRDATACADASTRO) VALUES (2,350,NULL,1,NOW());
INSERT INTO  PRECORANKING (PR_PRPOSRANKING,PR_PRPRECO,PR_PROBSERVACAO,PR_PRATIVO,PR_PRDATACADASTRO) VALUES (3,300,NULL,1,NOW());
INSERT INTO  PRECORANKING (PR_PRPOSRANKING,PR_PRPRECO,PR_PROBSERVACAO,PR_PRATIVO,PR_PRDATACADASTRO) VALUES (4,250,NULL,1,NOW());
INSERT INTO  PRECORANKING (PR_PRPOSRANKING,PR_PRPRECO,PR_PROBSERVACAO,PR_PRATIVO,PR_PRDATACADASTRO) VALUES (5,230,NULL,1,NOW());
INSERT INTO  PRECORANKING (PR_PRPOSRANKING,PR_PRPRECO,PR_PROBSERVACAO,PR_PRATIVO,PR_PRDATACADASTRO) VALUES (6,230,NULL,1,NOW());
INSERT INTO  PRECORANKING (PR_PRPOSRANKING,PR_PRPRECO,PR_PROBSERVACAO,PR_PRATIVO,PR_PRDATACADASTRO) VALUES (7,230,NULL,1,NOW());
INSERT INTO  PRECORANKING (PR_PRPOSRANKING,PR_PRPRECO,PR_PROBSERVACAO,PR_PRATIVO,PR_PRDATACADASTRO) VALUES (8,230,NULL,1,NOW());
INSERT INTO  PRECORANKING (PR_PRPOSRANKING,PR_PRPRECO,PR_PROBSERVACAO,PR_PRATIVO,PR_PRDATACADASTRO) VALUES (9,230,NULL,1,NOW());
INSERT INTO  PRECORANKING (PR_PRPOSRANKING,PR_PRPRECO,PR_PROBSERVACAO,PR_PRATIVO,PR_PRDATACADASTRO) VALUES (10,230,NULL,1,NOW());
USE FUTMESACARTOLA;
INSERT INTO  PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (11,200,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (12,200,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (13,200,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (14,200,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (15,200,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (16,200,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (17,200,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (18,200,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (19,200,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (20,200,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (21,190,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (22,190,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (23,190,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (24,190,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (25,190,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (26,190,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (27,190,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (28,190,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (29,190,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (30,190,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (31,180,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (32,180,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (33,180,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (34,180,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (35,180,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (36,180,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (37,180,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (38,180,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (39,180,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (40,170,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (41,170,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (42,170,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (43,170,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (44,170,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (45,170,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (46,170,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (47,170,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (48,170,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (49,170,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (50,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (51,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (52,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (53,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (54,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (55,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (56,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (57,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (58,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (59,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (60,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (61,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (62,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (63,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (64,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (65,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (66,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (67,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (68,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (69,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (70,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (71,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (72,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (73,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (74,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (75,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (76,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (77,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (78,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (79,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (80,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (81,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (82,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (83,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (84,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (85,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (86,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (87,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (88,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (89,160,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (90,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (91,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (92,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (93,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (94,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (95,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (96,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (97,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (98,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (99,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (100,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (101,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (102,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (103,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (104,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (105,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (106,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (107,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (108,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (109,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (110,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (111,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (112,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (113,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (114,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (115,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (116,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (117,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (118,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (119,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (120,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (121,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (122,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (123,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (124,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (125,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (126,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (127,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (128,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (129,140,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (130,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (131,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (132,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (133,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (134,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (135,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (136,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (137,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (138,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (139,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (140,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (141,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (142,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (143,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (144,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (145,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (146,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (147,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (148,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (149,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (150,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (151,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (152,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (153,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (154,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (155,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (156,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (157,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (158,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (159,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (160,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (161,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (162,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (163,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (164,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (165,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (166,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (167,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (168,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (169,120,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (170,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (171,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (172,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (173,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (174,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (175,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (176,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (177,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (178,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (179,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (180,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (181,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (182,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (183,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (184,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (185,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (186,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (187,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (188,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (189,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (190,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (191,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (192,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (193,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (194,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (195,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (196,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (197,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (198,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (199,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (200,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (201,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (202,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (203,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (204,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (205,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (206,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (207,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (208,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (209,100,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (210,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (211,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (212,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (213,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (214,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (215,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (216,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (217,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (218,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (219,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (220,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (221,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (222,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (223,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (224,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (225,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (226,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (227,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (228,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (229,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (230,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (231,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (232,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (233,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (234,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (235,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (236,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (237,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (238,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (239,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (240,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (241,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (242,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (243,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (244,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (245,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (246,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (247,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (248,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (249,80,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (250,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (251,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (252,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (253,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (254,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (255,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (256,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (257,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (258,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (259,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (260,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (261,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (262,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (263,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (264,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (265,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (266,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (267,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (268,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (269,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (270,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (271,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (272,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (273,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (274,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (275,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (276,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (277,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (278,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (279,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (280,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (281,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (282,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (283,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (284,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (285,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (286,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (287,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (288,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (289,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (290,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (291,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (292,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (293,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (294,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (295,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (296,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (297,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (298,60,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (299,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (300,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (301,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (302,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (303,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (304,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (305,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (306,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (307,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (308,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (309,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (310,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (311,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (312,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (313,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (314,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (315,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (316,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (317,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (318,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (319,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (320,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (321,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (322,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (323,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (324,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (325,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (326,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (327,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (328,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (329,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (330,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (331,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (332,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (333,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (334,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (335,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (336,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (337,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (338,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (339,40,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (340,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (341,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (342,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (343,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (344,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (345,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (346,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (347,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (348,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (349,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (350,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (351,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (352,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (353,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (354,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (355,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (356,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (357,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (358,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (359,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (360,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (361,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (362,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (363,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (364,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (365,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (366,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (367,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (368,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (369,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (370,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (371,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (372,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (373,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (374,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (375,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (376,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (377,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (378,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (379,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (380,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (381,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (382,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (383,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (384,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (385,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (386,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (387,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (388,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (389,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (390,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (391,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (392,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (393,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (394,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (395,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (396,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (397,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (398,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (399,20,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (400,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (401,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (402,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (403,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (404,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (405,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (406,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (407,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (408,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (409,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (410,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (411,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (412,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (413,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (414,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (415,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (416,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (417,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (418,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (419,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (420,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (421,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (422,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (423,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (424,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (425,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (426,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (427,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (428,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (429,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (430,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (431,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (432,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (433,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (434,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (435,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (436,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (437,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (438,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (439,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (440,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (441,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (442,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (443,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (444,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (445,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (446,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (447,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (448,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (449,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (450,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (451,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (452,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (453,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (454,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (455,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (456,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (457,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (458,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (459,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (460,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (461,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (462,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (463,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (464,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (465,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (466,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (467,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (468,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (469,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (470,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (471,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (472,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (473,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (474,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (475,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (476,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (477,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (478,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (479,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (480,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (481,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (482,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (483,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (484,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (485,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (486,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (487,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (488,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (489,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (490,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (491,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (492,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (493,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (494,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (495,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (496,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (497,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (498,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (499,10,NULL,1,NOW());
INSERT INTO PRECORANKING (PR_PRPOSRANKING, PR_PRPRECO, PR_PROBSERVACAO, PR_PRATIVO, PR_PRDATACADASTRO) VALUES (500,10,NULL,1,NOW());


 USE FUTMESACARTOLA;
  CREATE TABLE EQUIPES (
        EQ_EQID int AUTO_INCREMENT PRIMARY KEY,
        EQ_EQNOME VARCHAR(300) NOT NULL,
        EQ_USID int not null,
        EQ_EQESCUDO VARCHAR(500) NOT NULL,
        EQ_EQOBSERVACAO VARCHAR(300),
        EQ_EQATIVO boolean,
		EQ_EQDATACADASTRO Datetime
    );  
    
ALTER TABLE EQUIPES ADD CONSTRAINT FK_EQUIPES_Usuario FOREIGN KEY (EQ_USID) REFERENCES Usuario(US_USID);

 USE FUTMESACARTOLA;
  CREATE TABLE EQUIPESJOGADOR (
        EJ_EJID int AUTO_INCREMENT PRIMARY KEY,
        EJ_EQID INT NOT NULL,
        EJ_JOID int not null,
        EJ_EJOBSERVACAO VARCHAR(300),
        EJ_EJATIVO boolean,
		EJ_EJDATACADASTRO Datetime
    );  
  USE FUTMESACARTOLA;   
ALTER TABLE EQUIPESJOGADOR ADD CONSTRAINT FK_EQUIPESJOGADOR_Jogador FOREIGN KEY (EJ_JOID) REFERENCES Jogador(JO_JOID);
ALTER TABLE EQUIPESJOGADOR ADD CONSTRAINT FK_EQUIPESJOGADOR_Equipes FOREIGN KEY (EJ_EQID) REFERENCES EQUIPES(EQ_EQID);

 USE FUTMESACARTOLA;
  CREATE TABLE IMAGENSESCUDO (
        IM_IMIG int AUTO_INCREMENT PRIMARY KEY,
        IM_IMPATH varchar(400) NOT NULL,
        IM_IMOBSERVACAO VARCHAR(300),
        IM_IMATIVO boolean,
		IM_IMDATACADASTRO Datetime
    );  
USE FUTMESACARTOLA;
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/fpfm.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/cref.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/cmsp.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/SEP.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/SCCP.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('/assets/images/logos clubes/SPFC1.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('/assets/images/logos clubes/CFC.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/SAMZ.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/2004.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/FLA.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/MFC.png',NULL,1,Now());
USE FUTMESACARTOLA;
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/7SET.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/AFC.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/ATB.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/CAA.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/ECN.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/IPE.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/2004.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/ALZ.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/bfa.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/CAB.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/JAB.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/OPC.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/XV.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/AAB.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/ARP.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/CDB.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/NAC.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/POR.png',NULL,1,Now());
INSERT INTO IMAGENSESCUDO (IM_IMPATH,IM_IMOBSERVACAO,IM_IMATIVO,IM_IMDATACADASTRO) VALUES ('assets/images/logos clubes/LTV.png',NULL,1,Now());


 USE FUTMESACARTOLA;
 SELECT     A.JO_JOID, A.JO_JOAPELIDO, A.JO_JOFOTO, A.RJ_RJDATA, A.PR_PRPRECO,A.RJ_RJPOSICAO, B.RJ_RJPOSICAO,
			CASE 	WHEN  A.RJ_RJPOSICAO > B.RJ_RJPOSICAO THEN 'DESCE'
					WHEN  A.RJ_RJPOSICAO < B.RJ_RJPOSICAO THEN 'SOBE'
                    ELSE 'IGUAL'
			END AS STATUSPOSICAO,
            ABS(A.RJ_RJPOSICAO - B.RJ_RJPOSICAO) AS POSICOES
 FROM		(
			 SELECT		JO.JO_JOID, JO.JO_JOAPELIDO, JO.JO_JOFOTO, RJ.RJ_RJDATA, PR.PR_PRPRECO,RJ.RJ_RJPOSICAO,
						row_number() OVER (partition by JO.JO_JOID, JO.JO_JOAPELIDO, JO.JO_JOFOTO ORDER BY RJ.RJ_RJDATA DESC) AS CTR
			 FROM		JOGADOR JO
			 JOIN		RANKINGJOGADORES RJ ON JO.JO_JOID = RJ.RJ_JOID  
			 JOIN		PRECORANKING PR ON PR.PR_PRPOSRANKING = RJ.RJ_RJPOSICAO
			 WHERE		JO.JO_JOATIVO = 1
             ) A
JOIN		(SELECT	*
			 FROM	RANKINGJOGADORES RJ1
             JOIN	JOGADOR JO1 ON RJ1.RJ_JOID = JO1.JO_JOID ) B ON  B.JO_JOID = A.JO_JOID AND B.RJ_RJDATA = DATE_ADD(A.RJ_RJDATA, INTERVAL -1 MONTH)
WHERE 		A.CTR = 1


 
  USE FUTMESACARTOLA;
  SELECT DATEADD('2020-06-30', INTERVAL -1 MONTH)
  SELECT DATE_ADD("2017-06-15", INTERVAL 10 DAY); 
 SELECT * FROM PRECORANKING
 
 
 JO_JOID, JO.JO_JOAPELIDO, JO.JO_JOFOTO, RJ.RJ_RJDATA, PR.PR_PRPRECO,RJ.RJ_RJPOSICAO
 
 USE FUTMESACARTOLA;
SELECT RJ1.RJ_RJPOSICAO , JO1.JO_JOID
			 FROM	RANKINGJOGADORES RJ1
             JOIN	JOGADOR JO1 ON RJ1.RJ_JOID = JO1.JO_JOID
 
 