CREATE TABLE RANKINGJOGADORES (
        RJ_RJID int AUTO_INCREMENT PRIMARY KEY,
        RJ_RJMES int not null,
        RJ_RJANO int not null,
        RJ_RJDATA date not null,
        RJ_JOID int not null,
        RJ_RJPOSICAO int,
        RJ_RJOBSERVACAO VARCHAR(300),
        RJ_RJATIVO boolean,
		RJ_RJDATACADASTRO Datetime
    ); 
USE FUTMESACARTOLA;    
select * from RANKINGJOGADORES 
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (1,2020,'2020-01-01',2,1,NULL,1,NOW());
USE FUTMESACARTOLA;    
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (2,2020,'2020-02-01',2,12,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (3,2020,'2020-03-01',2,25,NULL,1,NOW());

INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (1,2020,'2020-01-01',3,250,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (2,2020,'2020-02-01',3,150,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (3,2020,'2020-03-01',3,80,NULL,1,NOW());

INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (1,2020,'2020-01-01',22,251,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (2,2020,'2020-02-01',22,155,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (3,2020,'2020-03-01',22,90,NULL,1,NOW());

INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (1,2020,'2020-01-01',23,100,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (2,2020,'2020-02-01',23,25,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (3,2020,'2020-03-01',23,15,NULL,1,NOW());


INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (1,2020,'2020-01-01',24,20,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (2,2020,'2020-02-01',24,2,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (3,2020,'2020-03-01',24,10,NULL,1,NOW());


INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (1,2020,'2020-01-01',25,50,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (2,2020,'2020-02-01',25,20,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (3,2020,'2020-03-01',25,11,NULL,1,NOW());

INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (1,2020,'2020-01-01',26,5,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (2,2020,'2020-02-01',26,30,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (3,2020,'2020-03-01',26,100,NULL,1,NOW());


INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (1,2020,'2020-01-01',27,50,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (2,2020,'2020-02-01',27,20,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (3,2020,'2020-03-01',27,15,NULL,1,NOW());

INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (1,2020,'2020-01-01',28,30,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (2,2020,'2020-02-01',28,25,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (3,2020,'2020-03-01',28,40,NULL,1,NOW());

INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (1,2020,'2020-01-01',29,50,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (2,2020,'2020-02-01',29,80,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (3,2020,'2020-03-01',29,150,NULL,1,NOW());

INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (1,2020,'2020-01-01',30,200,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (2,2020,'2020-02-01',30,120,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (3,2020,'2020-03-01',30,50,NULL,1,NOW());

USE FUTMESACARTOLA;
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (1,2020,'2020-01-01',31,100,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (2,2020,'2020-02-01',31,60,NULL,1,NOW());
INSERT INTO RANKINGJOGADORES (RJ_RJMES,RJ_RJANO,RJ_RJDATA,RJ_JOID,RJ_RJPOSICAO,RJ_RJOBSERVACAO,RJ_RJATIVO,RJ_RJDATACADASTRO) VALUES (3,2020,'2020-03-01',31,25,NULL,1,NOW());

    USE FUTMESACARTOLA;
    SELECT * FROM RANKINGJOGADORES