DROP PROCEDURE IF EXISTS SP_APURACAO;
DELIMITER |
CREATE PROCEDURE SP_APURACAO (IN IDCOMPETICAO INT )

BEGIN

    DECLARE EXIT HANDLER FOR SQLEXCEPTION 
        BEGIN
            ROLLBACK;
            SELECT 'APURACAO COM ERRO' AS RETORNO;
        END;

	START TRANSACTION;

	IF (IDCOMPETICAO = 0) THEN
		BEGIN
			DELETE FROM futmesacartola.APURACAOJOGADORES WHERE AJ_CPID <> 0;

			INSERT INTO APURACAOJOGADORES (AJ_AJDATAVIGENTE, AJ_CPID, AJ_CPDESCRICAO, AJ_ROID, AJ_RODESCRICAO, AJ_JOID, AJ_JOAPELIDO, AJ_EQID, AJ_EQNOME, AJ_USID, AJ_USNOMETRATAMENTO,  AJ_AJPONTOS, AJ_EQESCUDO) 
			SELECT  DISTINCT CP.CP_CPDATAINICIO,CP.CP_CPID, CP.CP_CPDESCRICAO, RO.RO_ROID, RO.RO_RODESCRICAO, JO.JO_JOID, JO.JO_JOAPELIDO, EQ.EQ_EQID, EQ.EQ_EQNOME
					, US.US_USID, US.US_USNOMETRATAMENTO, PJ.PJ_PJPONTOS, EQ.EQ_EQESCUDO
			FROM	futmesacartola.EQUIPES EQ
			JOIN	futmesacartola.EQUIPESJOGADOR EJ ON EQ.EQ_EQID = EJ.EJ_EQID
			JOIN	futmesacartola.PTSCOMPETICOESJOGADORES PJ ON PJ.PJ_JOID
			JOIN	futmesacartola.COMPETICOES CP ON CP.CP_CPID = PJ.PJ_CPID
			JOIN	futmesacartola.Jogador JO ON JO.JO_JOID = PJ.PJ_JOID
			JOIN	futmesacartola.RODADAS RO ON RO.RO_ROID = CP.CP_ROID
			JOIN	futmesacartola.Usuario US ON US.US_USID = EQ.EQ_USID
            WHERE   1 = 1 
            -- AND		EQ.EQUIPES.EQ_EQDATACADASTRO < CP.CP_CPQDATACADASTRO
            AND		EQ.EQ_EQATIVO = 1;
		END;
    ELSE
		BEGIN
        
			DELETE FROM APURACAOJOGADORES WHERE AJ_CPID = IDCOMPETICAO;

			INSERT INTO APURACAOJOGADORES (AJ_AJDATAVIGENTE, AJ_CPID, AJ_CPDESCRICAO, AJ_ROID, AJ_RODESCRICAO, AJ_JOID, AJ_JOAPELIDO, AJ_EQID, AJ_EQNOME, AJ_USID, AJ_USNOMETRATAMENTO,  AJ_AJPONTOS, AJ_EQESCUDO) 
			SELECT  DISTINCT CP.CP_CPDATAINICIO,CP.CP_CPID, CP.CP_CPDESCRICAO, RO.RO_ROID, RO.RO_RODESCRICAO, JO.JO_JOID, JO.JO_JOAPELIDO
							, EQ.EQ_EQID, EQ.EQ_EQNOME, US.US_USID, US.US_USNOMETRATAMENTO, PJ.PJ_PJPONTOS, EQ.EQ_EQESCUDO
			FROM	futmesacartola.EQUIPES EQ
			JOIN	futmesacartola.EQUIPESJOGADOR EJ ON EQ.EQ_EQID = EJ.EJ_EQID
			JOIN	futmesacartola.PTSCOMPETICOESJOGADORES PJ ON PJ.PJ_JOID
			JOIN	futmesacartola.COMPETICOES CP ON CP.CP_CPID = PJ.PJ_CPID
			JOIN	futmesacartola.Jogador JO ON JO.JO_JOID = PJ.PJ_JOID
			JOIN	futmesacartola.RODADAS RO ON RO.RO_ROID = CP.CP_ROID
			JOIN	futmesacartola.Usuario US ON US.US_USID = EQ.EQ_USID
			WHERE	1 = 1 
            -- AND		EQ.EQUIPES.EQ_EQDATACADASTRO < CP.CP_CPQDATACADASTRO
            AND		CP.CP_CPID = IDCOMPETICAO
            AND		EQ.EQ_EQATIVO = 1;
        END;
	END IF;
    
    SELECT 'APURACAO SUCESSO' AS RETORNO;
    COMMIT;
END
|
DELIMITER ;